image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

.build: &build
  stage: build
  script:
    - set -- $CI_BUILD_NAME
    - docker build -f "Dockerfile.$1" .

.release: &release
  stage: release
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_BUILD_NAME" -f "Dockerfile.$CI_BUILD_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_NAME"
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

SDK_TOOLS-25.2.3-SDK-25-BUILD_TOOLS-25.0.2 test: *test
SDK_TOOLS-25.2.3-SDK-25-BUILD_TOOLS-25.0.2: *release
